module.exports = [
  // ===== MARRIED MALE SCENARIOS =====
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_CHILDREN',
    description: 'Christian Male - Married with wife and children',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 1,
  },
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_NO_CHILDREN_FATHER',
    description: 'Christian Male - Married with wife, no children, father alive',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 2,
  },
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_NO_CHILDREN_NO_FATHER',
    description: 'Christian Male - Married with wife, no children, no father',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 3,
  },
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_DECEASED_CHILDREN',
    description: 'Christian Male - Married, wife deceased, with children',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 4,
  },
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_DECEASED_NO_CHILDREN_FATHER',
    description: 'Christian Male - Married, wife deceased, no children, father alive',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 5,
  },
  {
    case_id: 'CHRISTIAN_MALE_MARRIED_WIFE_DECEASED_NO_CHILDREN_NO_FATHER',
    description: 'Christian Male - Married, wife deceased, no children, no father',
    gender: 'male',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 6,
  },

  // ===== MARRIED FEMALE SCENARIOS =====
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_CHILDREN',
    description: 'Christian Female - Married with husband and children',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 1,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_NO_CHILDREN_FATHER',
    description: 'Christian Female - Married with husband, no children, father alive',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 2,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_NO_CHILDREN_NO_FATHER',
    description: 'Christian Female - Married with husband, no children, no father',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 3,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_DECEASED_CHILDREN',
    description: 'Christian Female - Married, husband deceased, with children',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 4,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_DECEASED_NO_CHILDREN_FATHER',
    description: 'Christian Female - Married, husband deceased, no children, father alive',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 5,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_MARRIED_HUSBAND_DECEASED_NO_CHILDREN_NO_FATHER',
    description: 'Christian Female - Married, husband deceased, no children, no father',
    gender: 'female',
    religion: 'christian',
    conditions: { married: true, spouse_alive: false, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 6,
  },

  // ===== UNMARRIED/DIVORCED SCENARIOS =====
  {
    case_id: 'CHRISTIAN_MALE_UNMARRIED_CHILDREN',
    description: 'Christian Male - Unmarried/Divorced with children',
    gender: 'male',
    religion: 'christian',
    conditions: { married: false, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 7,
  },
  {
    case_id: 'CHRISTIAN_MALE_UNMARRIED_NO_CHILDREN_FATHER',
    description: 'Christian Male - Unmarried/Divorced, no children, father alive',
    gender: 'male',
    religion: 'christian',
    conditions: { married: false, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 8,
  },
  {
    case_id: 'CHRISTIAN_MALE_UNMARRIED_NO_CHILDREN_NO_FATHER',
    description: 'Christian Male - Unmarried/Divorced, no children, no father',
    gender: 'male',
    religion: 'christian',
    conditions: { married: false, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 9,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_UNMARRIED_CHILDREN',
    description: 'Christian Female - Unmarried/Divorced with children',
    gender: 'female',
    religion: 'christian',
    conditions: { married: false, has_children: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 7,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_UNMARRIED_NO_CHILDREN_FATHER',
    description: 'Christian Female - Unmarried/Divorced, no children, father alive',
    gender: 'female',
    religion: 'christian',
    conditions: { married: false, has_children: false, father_alive: true },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 8,
  },
  {
    case_id: 'CHRISTIAN_FEMALE_UNMARRIED_NO_CHILDREN_NO_FATHER',
    description: 'Christian Female - Unmarried/Divorced, no children, no father',
    gender: 'female',
    religion: 'christian',
    conditions: { married: false, has_children: false, father_alive: false },
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 9,
  },

  // ===== FALLBACK RULES =====
  {
    case_id: 'CHRISTIAN_FALLBACK',
    description: 'Christian Fallback - No eligible heirs',
    gender: 'both',
    religion: 'christian',
    conditions: {},
    heirs: [],
    source: 'Indian Succession Act, 1925',
    priority: 999,
  }
];