module.exports = [
  {
    case_id: 'MALE_MARRIED',
    description: 'Male - Married scenario - Dynamic inheritance calculation',
    gender: 'male',
    religion: 'hindu',
    conditions: { married: true },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
  {
    case_id: 'MALE_DIVORCED',
    description: 'Male - Divorced scenario - Dynamic inheritance calculation',
    gender: 'male',
    religion: 'hindu',
    conditions: { divorced: true },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
  {
    case_id: 'MALE_UNMARRIED',
    description: 'Male - Never Married scenario - Dynamic inheritance calculation',
    gender: 'male',
    religion: 'hindu',
    conditions: { married: false, divorced: false },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
  {
    case_id: 'FEMALE_MARRIED',
    description: 'Female - Married scenario - Dynamic inheritance calculation',
    gender: 'female',
    religion: 'hindu',
    conditions: { married: true },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
  {
    case_id: 'FEMALE_DIVORCED',
    description: 'Female - Divorced scenario - Dynamic inheritance calculation',
    gender: 'female',
    religion: 'hindu',
    conditions: { divorced: true },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
  {
    case_id: 'FEMALE_UNMARRIED',
    description: 'Female - Never Married scenario - Dynamic inheritance calculation',
    gender: 'female',
    religion: 'hindu',
    conditions: { married: false, divorced: false },
    heirs: [],
    source: 'Hindu Succession Act - Simplified Logic',
    priority: 10,
  },
];
