module.exports = [
  // ===== MARRIED MALE SCENARIOS =====
  {
    case_id: 'MUSLIM_MALE_MARRIED_WIFE_CHILDREN',
    description: 'Muslim Male - Married with wife and children',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: true, has_children: true },
    heirs: ['wife', 'children'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 1,
  },
  {
    case_id: 'MUSLIM_MALE_MARRIED_WIFE_NO_CHILDREN_PARENTS',
    description: 'Muslim Male - Married with wife, no children, parents alive',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: true, mother_alive: true },
    heirs: ['wife', 'father', 'mother'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 2,
  },
  {
    case_id: 'MUSLIM_MALE_MARRIED_WIFE_NO_CHILDREN_NO_PARENTS',
    description: 'Muslim Male - Married with wife, no children, no parents',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: false, mother_alive: false },
    heirs: ['wife', 'siblings'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 3,
  },
  {
    case_id: 'MUSLIM_MALE_MARRIED_WIFE_DECEASED_CHILDREN',
    description: 'Muslim Male - Married, wife deceased, with children',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: false, has_children: true },
    heirs: ['children'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 4,
  },
  {
    case_id: 'MUSLIM_MALE_MARRIED_WIFE_DECEASED_NO_CHILDREN_PARENTS',
    description: 'Muslim Male - Married, wife deceased, no children, parents alive',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: false, has_children: false, father_alive: true, mother_alive: true },
    heirs: ['father', 'mother'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 5,
  },

  // ===== MARRIED FEMALE SCENARIOS =====
  {
    case_id: 'MUSLIM_FEMALE_MARRIED_HUSBAND_CHILDREN',
    description: 'Muslim Female - Married with husband and children',
    gender: 'female',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: true, has_children: true },
    heirs: ['husband', 'children'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 1,
  },
  {
    case_id: 'MUSLIM_FEMALE_MARRIED_HUSBAND_NO_CHILDREN_PARENTS',
    description: 'Muslim Female - Married with husband, no children, parents alive',
    gender: 'female',
    religion: 'muslim',
    conditions: { married: true, spouse_alive: true, has_children: false, father_alive: true, mother_alive: true },
    heirs: ['husband', 'father', 'mother'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 2,
  },

  // ===== UNMARRIED/DIVORCED SCENARIOS =====
  {
    case_id: 'MUSLIM_MALE_UNMARRIED_CHILDREN',
    description: 'Muslim Male - Unmarried/Divorced with children',
    gender: 'male',
    religion: 'muslim',
    conditions: { married: false, has_children: true },
    heirs: ['children'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 6,
  },
  {
    case_id: 'MUSLIM_FEMALE_UNMARRIED_CHILDREN',
    description: 'Muslim Female - Unmarried/Divorced with children',
    gender: 'female',
    religion: 'muslim',
    conditions: { married: false, has_children: true },
    heirs: ['children'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 6,
  },

  // ===== FALLBACK RULES =====
  {
    case_id: 'MUSLIM_FALLBACK',
    description: 'Muslim Fallback - No eligible heirs',
    gender: 'both',
    religion: 'muslim',
    conditions: {},
    heirs: ['residuary_heirs'],
    source: 'Muslim Personal Law (Sharia)',
    priority: 999,
  }
];